name: GenerateJRES

on:
  push:
    paths:
      - 'resources/generate-extraicons.js'
      - '**.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Generate SVG images
      run: node resources/generate-extraicons.js
      shell: bash
    - name: Convert SVG to PNG
      uses: joergnapp/convert-svg-to-png@main
      with:
        svgpath: 'resources/extraicons/svg/'
        pngpath: 'resources/extraicons/png/'
    - name: Generate JRES file
      run: node resources/generate-jres.js
      shell: bash
    - name: List repository contents (for debugging)
      run: |
        ls -R
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref || github.ref_name }}
        message: 'Auto-generation JRES'
