name: GenerateJRES

on:
  push:
    paths:
      - 'resources/generate-extraicons.js'
      - '**.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0             # otherwise, you will fail to push refs to dest repo
#    - name: Setup Node.js
#      uses: actions/setup-node@v4
#      with:
#        node-version: 18
    - name: Generate SVG images
      run: node resources/generate-extraicons.js
      shell: bash
    - name: Convert SVG to PNG
      uses: joergnapp/convert-svg-to-png@main
      with:
        svgpath: 'resources/extraicons/'
        pngpath: 'jres/extraicons/'
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install PXT
      run: npm install -g pxt
    - name: Generate JRES
      run: pxt jres
    - name: List repository contents (for debugging)
      run: |
        ls -R
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master'
        message: 'Auto-generation JRES'
